plugins {
	id 'java-library'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'javax.servlet:javax.servlet-api:4.0.1'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
		vendor = JvmVendorSpec.ADOPTIUM
	}

	compileJava {
		options.release = 17
	}
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }

	test {
		java {
			srcDirs = ['test']
		}
	}
}

description = 'Gradle build script for code examples in Head First Design Patterns book'
group = 'headfirst.designpatterns'
