---
name: "CI"
on:
  - push
  - pull_request

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  validate:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  build:
    name: "Build project"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Gradle build
        run: ./gradlew build
